theme: minima
title: VegBlog
author: Nonna Salix
email: mg.sperandii@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ..and don't worry about losing. If it is right, it happens. The main thing is not to hurry. Nothing good gets away.
# social links
twitter_username: mgsperandii # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
